import PDFDocument from "pdfkit";
import fs from "fs";

/**
 * Generates PDF for a single application
 * @param {Object} application - Application data from DB
 * @param {Array} documents - Array of document info [{filename, ipfs_hash}]
 * @param {String} outputPath - Path to save PDF
 */
function generateApplicationPDF(application, documents, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(outputPath);
      doc.pipe(stream);

      // Header
      doc.fontSize(20).text("Application Summary", { align: "center" });
      doc.moveDown();

      // Application Info
      doc.fontSize(12).text(`Application ID: ${application.id || ""}`);
      doc.text(`Service Type: ${application.license_type || ""}`);
      doc.text(`Status: ${application.status || ""}`);
      doc.text(`Submitted On: ${application.submission_date || ""}`);
      doc.moveDown();

      // Applicant Details
      doc.text("Applicant Details:", { underline: true });

      let appData = application.application_data;
      if (typeof appData === "string") {
        try {
          appData = JSON.parse(appData);
        } catch {
          appData = {};
        }
      }

      Object.entries(appData || {}).forEach(([step, fields]) => {
        doc.moveDown(0.5).text(`${step}:`, { bold: true });
        Object.entries(fields).forEach(([key, value]) => {
          doc.text(`  ${key}: ${value}`);
        });
      });
      doc.moveDown();

      // Documents
      if (documents?.length) {
        doc.text("Uploaded Documents:", { underline: true });
        documents.forEach((d, i) => {
          doc.text(`${i + 1}. ${d.original_name} - IPFS: ${d.ipfs_hash}`);
        });
      }

      // Footer
      doc.moveDown();
      doc.font("Times-Italic").text("Generated by DigiSewa", { align: "center" });

      doc.end();

      stream.on("finish", () => resolve(outputPath));
      stream.on("error", reject);
    } catch (err) {
      reject(err);
    }
  });
}

export { generateApplicationPDF };
