// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fotsoyglzlfwfyiozbee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvdHNveWdsemxmd2Z5aW96YmVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDc3NTMsImV4cCI6MjA2NzYyMzc1M30.lV3B8LjLPquuf0EUcIn-RTbqdF2PAYTx58pf0sn565w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});